x-base: &backend-base
  build: .
  env_file:
    - .env
  depends_on:
    - db
  volumes:
    - ./task_manager:/opt/task_manager

services:
  db:
    container_name: task_manager_db
    image: postgres:18.0-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  migrate:
    <<: *backend-base
    entrypoint: ['sh', './entrypoints/entrypoint.sh']
    container_name: task_manager_migrate
    image: task_manager_migrate_image
    restart: "no"

  backend:
    <<: *backend-base
    entrypoint: ['python3', './manage.py', 'runserver', '0.0.0.0:8000']
    container_name: task_manager_backend
    image: task_manager_backend_image
    ports:
      - "8000:8000"
    restart: unless-stopped